FROM alpine:3.21

ARG TARGETPLATFORM

RUN apk add --no-cache ca-certificates tzdata

COPY $TARGETPLATFORM/homeocto /usr/local/bin/homeocto
COPY $TARGETPLATFORM/homeocto-launcher /usr/local/bin/homeocto-launcher

ENTRYPOINT ["homeocto-launcher"]
CMD ["-console", "-public", "-no-browser"]
